apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"k8s-app":"kubeedge","kubeedge":"cloudcore"},"name":"cloudcore-svc-np","namespace":"kubeedge"},"spec":{"ports":[{"name":"cloudhub","nodePort":30000,"port":10000,"protocol":"TCP","targetPort":10000},{"name":"cloudhub-quic","nodePort":30001,"port":10001,"protocol":"TCP","targetPort":10001},{"name":"cloudhub-https","nodePort":30002,"port":10002,"protocol":"TCP","targetPort":10002},{"name":"cloudstream","nodePort":30003,"port":10003,"protocol":"TCP","targetPort":10003},{"name":"tunnelport","nodePort":30004,"port":10004,"protocol":"TCP","targetPort":10004}],"selector":{"k8s-app":"kubeedge","kubeedge":"cloudcore"},"sessionAffinity":"None","type":"NodePort"}}
  creationTimestamp: "2022-12-23T12:07:14Z"
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
    velero.io/backup-name: edge-test-2-pdkdb-6c97r
    velero.io/restore-name: restore-edge-1-7mcjl-zbzdj
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:k8s-app: {}
          f:kubeedge: {}
          f:velero.io/backup-name: {}
          f:velero.io/restore-name: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":10000,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:nodePort: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":10001,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:nodePort: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":10002,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:nodePort: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":10003,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:nodePort: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":10004,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:nodePort: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:k8s-app: {}
          f:kubeedge: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: velero-server
    operation: Update
    time: "2022-12-23T12:07:14Z"
  name: cloudcore-svc-np
  namespace: kubeedge
  resourceVersion: "175130677"
  selfLink: /api/v1/namespaces/kubeedge/services/cloudcore-svc-np
  uid: 7f4fe761-1a25-47e1-9027-7189015b8147
spec:
  clusterIP: 10.96.2.235
  externalTrafficPolicy: Cluster
  ports:
  - name: cloudhub
    nodePort: 30000
    port: 10000
    protocol: TCP
    targetPort: 10000
  - name: cloudhub-quic
    nodePort: 30001
    port: 10001
    protocol: TCP
    targetPort: 10001
  - name: cloudhub-https
    nodePort: 30002
    port: 10002
    protocol: TCP
    targetPort: 10002
  - name: cloudstream
    nodePort: 30003
    port: 10003
    protocol: TCP
    targetPort: 10003
  - name: tunnelport
    nodePort: 30004
    port: 10004
    protocol: TCP
    targetPort: 10004
  selector:
    k8s-app: kubeedge
    kubeedge: cloudcore
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
