apiVersion: v1
kind: Namespace
metadata:
  name: edge-test
---
apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  namespace: edge-test
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/edge 
            operator: Exists
  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"
  containers:
    - command:
        - sleep
        - "infinite"
      image: busybox
      name: pods-simple-container
