{
 "title": "Backup stat",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Overall backup success rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(increase(backupjob_result{status!=\"Failed\"}[10y]) or increase(backupjob_result{export_status=\"Failed\"}[10y])) * 100/count(increase(backupjob_result[10y]))"
    }
   ]
  },
  {
   "title": "Processing PVC data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "processing_volume_backup_size_bytes unless on(backupjob) backupjob_result",
     "legendFormat": "{{backupjob}}"
    }
   ]
  },
  {
   "title": "Last backup time cost",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backupjob_processing_duration_seconds",
     "legendFormat": "{{backupplan}}"
    }
   ]
  },
  {
   "title": "Last export time cost",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backupjob_export_duration_seconds",
     "legendFormat": "{{backupplan}}"
    }
   ]
  },
  {
   "title": "Backup time cost by plan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "backupjob_processing_duration_seconds",
     "legendFormat": "{{backupplan}}"
    }
   ]
  },
  {
   "title": "Export time cost by plan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "backupjob_export_duration_seconds",
     "legendFormat": "{{backupplan}}"
    }
   ]
  }
 ]
}