{
 "title": "POD perf",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "ns",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "POD CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "\tsum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"$ns\"}[5m]))"
    }
   ]
  },
  {
   "title": "POD Mem usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_rss{namespace=\"$ns\", container_name!=\"POD\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container request CPU used percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 * max(\n  rate(container_cpu_usage_seconds_total{namespace=\"$ns\"}[5m])\n    / on (container, pod)\n  kube_pod_container_resource_limits{resource=\"cpu\"}\n) by (pod)"
    }
   ]
  },
  {
   "title": "Container request memory used percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100 * container_memory_working_set_bytes{namespace=\"$ns\"} / on (container, pod) kube_pod_container_resource_limits{resource=\"memory\"}"
    }
   ]
  },
  {
   "title": "POD network bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_network_receive_bytes_total{namespace=\"$ns\"}[5m]) + rate(container_network_transmit_bytes_total{namespace=\"$ns\"}[5m]))"
    }
   ]
  },
  {
   "title": "POD disk throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{namespace=\"$ns\"}[5m])) + sum by(pod) (rate(container_fs_writes_bytes_total{namespace=\"$ns\"}[5m]))"
    }
   ]
  }
 ]
}