{
 "title": "YS1000 DR Monitor",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Dr Config Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "dr_config_status",
     "legendFormat": "{{name}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Dr Instance Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dr_instance_status", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Data RPO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "dr_instance_data_current_rpo", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Resource RPO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "dr_instance_resource_current_rpo",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Applicatin State",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(dr_instance_status) by (app_state, name, primary_cluster, secondary_cluster)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}