apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    release: prometheus
  name: ys1000-dr-alerts
  namespace: qiming-migration # please change to match the namespace that YS1000 is installed into.
spec:
  groups:
    - name: ys1000-dr-healthy
      rules:
        - alert: DrConfigNotReady
          annotations:
            description: DrConfig {{$labels.name}} is not ready.
            summary: DrConfig {{$labels.name}} is not ready.
            content: "DrConfig {{$labels.name}} is not ready, please check immediately. errors: {{$labels.errors}}. warnings: {{$labels.warnings}}."
          expr: |-
            absent(up{service="dr_config_status"} == 0)
          for: 5m
          labels:
            severity: critical
            namespace: qiming-migration
        - alert: DrInstanceNotReady
          annotations:
            description: DrInstance {{$labels.name}} is not ready.
            summary: DrInstance {{$labels.name}} is not ready.
            content: "DrInstance {{$labels.name}} is not ready, please check immediately. errors: {{$labels.errors}}. warnings: {{$labels.warnings}}."
          expr: |-
            absent(up{service="dr_instance_status"} == 0)
          for: 5m
          labels:
            severity: critical
            namespace: qiming-migration
        - alert: DrInstanceDataRPOLagging
          annotations:
            description: DrInstance {{$labels.name}} data rpo lagging.
            summary: DrInstance {{$labels.name}} data rpo lagging more than 5 minutes.
            content: "DrInstance {{$labels.name}} data rpo lagging more than 5 minutes. current lagging: {{ $value }}s)"
          expr: |-
            absent(up{service="dr_instance_data_expected_rpo-dr_instance_data_current_rpo"} > 300)
          for: 5m
          labels:
            severity: warnings
            namespace: qiming-migration
        - alert: DrInstanceDataRPOLaggingLong
          annotations:
            description: DrInstance {{$labels.name}} data rpo lagging long.
            summary: DrInstance {{$labels.name}} data rpo lagging more than 10 hours.
            content: "DrInstance {{$labels.name}} data rpo lagging more than 10 hours. current lagging: {{ $value }}s)"
          expr: |-
            absent(up{service="dr_instance_data_expected_rpo-dr_instance_data_current_rpo"} > 36000)
          for: 5m
          labels:
            severity: critical
            namespace: qiming-migration
        - alert: DrInstanceResourceRPOLagging
          annotations:
            description: DrInstance {{$labels.name}} resource rpo lagging.
            summary: DrInstance {{$labels.name}} resource rpo lagging more than 5 minutes.
            content: "DrInstance {{$labels.name}} resource rpo lagging more than 5 minutes. current lagging: {{ $value }}s)"
          expr: |-
            absent(up{service="dr_instance_resource_expected_rpo-dr_instance_resource_current_rpo"} > 300)
          for: 5m
          labels:
            severity: warnings
            namespace: qiming-migration
        - alert: DrInstanceResourceRPOLaggingLong
          annotations:
            description: DrInstance {{$labels.name}} resource rpo lagging long.
            summary: DrInstance {{$labels.name}} resource rpo lagging more than 10 hours.
            content: "DrInstance {{$labels.name}} resource rpo lagging more than 10 hours. current lagging: {{ $value }}s)"
          expr: |-
            absent(up{service="dr_instance_resource_expected_rpo-dr_instance_resource_current_rpo"} > 36000)
          for: 5m
          labels:
            severity: critical
            namespace: qiming-migration
