apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cce-demo.fullname" . }}-config
  labels:
    {{- include "cce-demo.labels" . | nindent 4 }}
data:
  .filebrowser.json: |
    {{- tpl .Values.config $ | nindent 4 }}
