---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cce-demo.fullname" . }}-pvc
  labels:
    {{- include "cce-demo.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
